[format]
code = "thun"
name = "Magic Club Thun Clubformat"
deck_size = 60
sideboard_size = 15
max_copies = 3
singleton = false
commander_required = false

[legality]
allowed_rarities = ["common", "uncommon"]
paper_only = true
allow_digital = false
allow_acorn = false
allow_bonus_sheets = false
allow_special_guests = false

[sets]
starting_set = "bfz"

blocked_sets = [
    "rtr",
    "gtc",
    "dgm",
    "m14",
    "ths",
    "bng",
    "jou",
    "m15",
    "ktk",
    "frf",
    "dtk",
    "ori",
]